// packages/vue/src/TickerOnStart.vue
<script setup lang="ts">
import { onUnmounted, ref, watch } from "vue";

const running = ref(false);
const count = ref(0);
let intervalId: ReturnType<typeof setInterval> | undefined;

watch(running, (isRunning) => {
  if (intervalId) {
    clearInterval(intervalId);
    intervalId = undefined;
  }
  if (!isRunning) return;

  intervalId = setInterval(() => {
    count.value += 1;
  }, 1_000);
});

onUnmounted(() => {
  if (intervalId) clearInterval(intervalId);
});
</script>

<template>
  <div>
    <div role="status" aria-label="count">{{ count }}</div>
    <button type="button" aria-label="start" @click="running = true">start</button>
  </div>
</template>

// packages/angular/src/TickerOnStartComponent.ts
import { Component, signal } from "@angular/core";

@Component({
  selector: "app-ticker-on-start",
  standalone: true,
  template: `
    <div>
      <div role="status" aria-label="count">{{ count() }}</div>
      <button type="button" aria-label="start" (click)="start()">start</button>
    </div>
  `,
})
export class TickerOnStartComponent {
  count = signal(0);
  private intervalId?: ReturnType<typeof setInterval>;

  start() {
    if (this.intervalId) return;

    this.intervalId = setInterval(() => {
      this.count.update((value) => value + 1);
    }, 1_000);
  }
}
