// packages/vue/src/TickerOnStart.vue
<script setup lang="ts">
import { onUnmounted, ref, watch } from "vue";

const running = ref(false);
const count = ref(0);
let intervalId: ReturnType<typeof setInterval> | undefined;

watch(running, (isRunning) => {
  if (intervalId) {
    clearInterval(intervalId);
    intervalId = undefined;
  }
  if (!isRunning) return;

  intervalId = setInterval(() => {
    count.value += 1;
  }, 1_000);
});

onUnmounted(() => {
  if (intervalId) clearInterval(intervalId);
});
</script>

<template>
  <div>
    <div role="status" aria-label="count">{{ count }}</div>
    <button type="button" aria-label="start" @click="running = true">start</button>
  </div>
</template>

// packages/svelte/src/TickerOnStart.svelte
<script lang="ts">
  let running = $state(false);
  let count = $state(0);

  $effect(() => {
    if (!running) return;

    const intervalId = setInterval(() => {
      count += 1;
    }, 1_000);

    return () => clearInterval(intervalId);
  });
</script>

<div>
  <div role="status" aria-label="count">{count}</div>
  <button type="button" aria-label="start" onclick={() => (running = true)}>start</button>
</div>
