// packages/react/src/given.ts
import { render } from "@testing-library/react";
import type { GivenStep } from "@siheom/core";
import type { ReactElement } from "react";

export const defaultGivens = {
  render: async (element: ReactElement) => {
    render(element);
  },
};

export const given = {
  render: (element: ReactElement): GivenStep<typeof defaultGivens> => ({
    given: "render",
    log: "렌더한다",
    args: [element],
  }),
};

// packages/qwik/src/given.ts
import { render } from "@noma.to/qwik-testing-library";
import type { GivenStep } from "@siheom/core";
import type { JSXOutput } from "@builder.io/qwik";

export const defaultGivens = {
  render: async (element: JSXOutput) => {
    await render(element);
  },
};

export const given = {
  render: (element: JSXOutput): GivenStep<typeof defaultGivens> => ({
    given: "render",
    log: "렌더한다",
    args: [element],
  }),
};
